# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
