# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 20:21
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('dni', models.CharField(blank=True, max_length=9, null=True)),
                ('company_name', models.CharField(blank=True, max_length=254)),
                ('nif', models.CharField(blank=True, max_length=10)),
                ('billing_address', models.CharField(blank=True, max_length=254)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[(b'buyer', b'Comprador'), (b'seller', b'Vendedor')], default='seller', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
