# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_type', models.CharField(choices=[(b'transfer', b'Transferencia'), (b'metal', 'Met\xe1lico')], default='transfer', max_length=10)),
                ('status', models.CharField(choices=[(b'accepted', b'Aceptada'), (b'refused', b'Rechazada'), (b'canceled', b'Cancelada'), (b'pending', b'Pendiente')], default='pending', max_length=10)),
                ('offer_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
