# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20171129_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='payment_type',
            field=models.CharField(choices=[('transfer', 'Transferencia'), ('metal', 'Metálico')], default='transfer', max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('accepted', 'Aceptada'), ('refused', 'Rechazada'), ('canceled', 'Cancelada'), ('pending', 'Pendiente')], default='pending', max_length=10),
        ),
    ]
